import { Injectable, Inject } from '@angular/core';
import { Globals } from 'app/globals';

@Injectable()
export class ApiEndPoints {
    constructor(private globals: Globals) {
        Inject(Globals);
        if (this.globals.EnableWSO2EndPoints) {

        }
    }

    public apiUrls = {
        "eapps": {
            "loginUserDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/loginUserDetails',
            "getCitiesAndStates": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCitiesAndStates',
            "getStateByCityCode": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getStateByCityCode',
            "getGSTStateCode": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getGSTStateCode',
            "getBranchMasterDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getBranchMasterDetails',
            "getInternalAgentDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getInternalAgentDetails',
            "getAgentDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAgentDetails',
            "getPartieDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPartieDetails',
            "fetchPartyDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchPartyDetails',
            "getBDO": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getBDO',
            "getAgentBDO": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAgentBDO',
            "getOccupation": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getOccupation',
            "getPOS": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPOS',
            "getPosAgentDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPosAgentDetails',
            "getCoverNotes": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCoverNotes',
            "getCoverNoteDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCoverNoteDetails',
            "getInsuranceRepositories": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getInsuranceRepositories',
            "getRTO": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getRTO',
            "getVechileDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getVechileDetails',
            "getRegRegionZone": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getRegRegionZone',
            "getAvailableMakes": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAvailableMakes',
            "getModelData": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getModelData',
            "getModelsForMake": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getModelsForMake',
            "getTechnicalDiscountDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getTechnicalDiscountDetails',
            "getServiceProviders": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getServiceProviders',
            "getAutoAssociations": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAutoAssociations',
            "getAddonCoverageForExternalUser": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAddonCoverageForExternalUser',
            "getCampaignDiscounts": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCampaignDiscounts',
            "getFraudReasons": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getFraudReasons',
            "getMasterData": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getMasterData',
            "getPreviousInsurers": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPreviousInsurers',
            "getCompanyBranches": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCompanyBranches',
            "getCompanyBranchAddress": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCompanyBranchAddress',
            "getCommissionDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCommissionDetails',
            "getMotorCoverages": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getMotorCoverages',
            "getHealthCoverages": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getHealthCoverages',
            "getFloaterRelations": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getFloaterRelations',
            "getHomeCoverages": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getHomeCoverages',
            "getPincodeMasterDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPincodeMasterDetails',
            "getOccupations": `${this.globals.URLPREFIXHOME}getOccupations`,
            "getMasterOccupations": `${this.globals.URLPREFIXHOME}getMasterOccupations`,
            "saveMotorQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/saveMotorQuote',
            "getAgents": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAgents',
            "searchParties": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/searchParties',
            "getExternalCoverNoteDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getExternalCoverNoteDetails',
            "getNomineeRelationship": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getNomineeRelationship',
            "fetchSchemeCodeList": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchSchemeCodeList',
            "getTrailerMakes": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getTrailerMakes',
            "getTrailerModels": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getTrailerModels',
            "getCampaignDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCampaignDetails',
            "checkGroupCampaign": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/checkGroupCampaign',
            "fetchProductForPolicyForNB": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchProductForPolicyForNB',
            "getLivesCoveredCampaigns": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getLivesCoveredCampaigns',
            "getPlansForCampaign": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPlansForCampaign',
            "getIdentityProofs": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getIdentityProofs',
            "getResidenceProofs": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getResidenceProofs',
            "getRiders": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getRiders',
            "getPreAilments": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPreAilments',
            "getICDDesc": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getICDDesc',
            "saveHealthQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/saveHealthQuote',
            "updateCheckListFilled": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/updateCheckListFilled',
            "saveHomeQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/saveHomeQuote',
            "getAdditionalInfoPropForAgents": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAdditionalInfoPropForAgents',
            "getGender": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getGender',
            "checkIfCheckListFilled": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/checkIfCheckListFilled',
            "getChkList": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getChkList',
            "searchHealthPolicy": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/searchHealthPolicy',
            "getMasterPlanList": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getMasterPlanList',
            "getMasterSubPlanList": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getMasterSubPlanList',
            "getFOSProductPlans": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getFOSProductPlans',
            "showCoverageOptionPartner": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/showCoverageOptionPartner',
            "getCampaignNames": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getCampaignNames',
            "getProducts": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getProducts`,
            "getAgentProducts": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAgentProducts',
            "isCombiProduct": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/isCombiProduct',
            "fetchCombiSumInsureds": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchCombiSumInsureds',
            "getInsuranceCompanyNames": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getInsuranceCompanyNames',
            "getICDCodeFromMasterDisease": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getICDCodeFromMasterDisease',
            "getPEPName": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPEPName',
            "getNameFromCommonItem": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getNameFromCommonItem',
            "getPreviousPolicyDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPreviousPolicyDetails',
            "mobileNumberValidation": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/mobileNumberValidation',
            "getBreakInLoading": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getBreakInLoading',
            "getReasons": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getReasons',
            "checkCombiCampaign": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/checkCombiCampaign',
            "cancelQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/cancelQuote',
            "fetchQuestions": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchQuestions',
            "getBanks": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getBanks',
            "getBodyType": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getBodyType',
            "getHypothecation": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getHypothecation',
            "getMessageDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getMessageDetails',
            "approveMessageDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/approveMessageDetails',
            "getSublineForInsPolicy": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getSublineForInsPolicy',
            "getModuleDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getModuleDetails',
            "getMessages": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getMessages',
            "getPolicyId": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getPolicyId`,
            "fetchTasks": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/fetchTasks`,
            "releaseTask": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}` + `/releaseTask`,
            "getDITCampaigns": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getDITCampaigns`,
            "getInwardDetails": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getInwardDetails`,
            "getDetails": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getDetails`,
            "viewReasons": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/viewReasons`,
            "processShortfallCollected": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/processShortfallCollected`,
            "viewHistory": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/viewHistory`,
            "viewHumsErrors": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/viewHumsErrors`,
            "viewComments": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/viewComments`,
            "getInfopendingReasons": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getInfopendingReasons`,
            "getUserAgentSegmentMappings": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getUserAgentSegmentMappings`,
            "getRmCode": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getRmCode`,
            "getBDOCode": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getBDOCode`,
            "getPolicyIds": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getPolicyIds`,
            "createReceiptNo": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/createReceiptNo`,
            "approveChequeDishonourInward": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/approveChequeDishonourInward`,
            "createInward": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/createInward`,
            "inwardSummaryPage": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/inwardSummaryPage`,
            "saveEditDetails": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/saveEditDetails`,
            "getUploadedDocuments": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/getUploadedDocuments`,
            "searchInward": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/searchInward`,
            "sentforProcessing": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/sentforProcessing`,
            "sendToInfoPending": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/sendToInfoPending`,
            "sentToInvalid": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/sentToInvalid`,
            "revokeProposal": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/revokeProposal`,
            "sentToRefund": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/sentToRefund`,
            "documentUpload": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/documentUpload`,
            "searchChequeDishonourInward": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/searchChequeDishonourInward`,
            "generateChequeDishonourPdf": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/generateChequeDishonourPdf',
            "getAvaliableEndorsements": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAvaliableEndorsements',
            "getClaimDetailsService": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getClaimDetailsService',
            "getHealthCombiCoveragesandQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getHealthCombiCoveragesandQuote',
            "loadPolicy": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/loadPolicy',
            "getHealthCombiOTPValidate": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getHealthCombiOTPValidate',
            "getOtpforHealthCombi": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + `/getOtpforHealthCombi`,
            "customerApprove": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + `/customerApprove`,
            "sendToFinance": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + `/sendToFinance`,
            "getOTPAcceptAndPendingCases": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + `/getOTPAcceptAndPendingCases`,
            "getPolicyHistory": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPolicyHistory',
            "postEndorsementDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/postEndorsementDetails',
            "getPolicyDetailsForEndorsement": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPolicyDetailsForEndorsement',
            "getExpiryDate": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getExpiryDate',
            "getProposalDocuments": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getProposalDocuments',
            "getPayementModes": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getPayementModes',
            "getAllReceiptsForPolicies": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAllReceiptsForPolicies',
            "submitPayment": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + `/travelPolicy/submitPayment`,
            "getPolicyDetails": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/travelPolicy/getPolicyDetails`,
            "sendLinktoCustomer": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/sendLinktoCustomer',
            "searchPolicy": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/searchPolicy',
            "saveAndProcess": `${this.globals.BACKEND_URL_PREFIX}${this.globals.CONTEXT_PATH}/saveAndProcess`,
            "finalizeEndorsement": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/finalizeEndorsement',
            "deleteEndorsement": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/deleteEndorsement',
            "getViewAddonCovers": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getViewAddonCovers',
            "generatePrint": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/generatePrint',
            "generateAutoReceipt": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/generateAutoReceipt',
            "getAlertMessageReason": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getAlertMessageReason',
            "processPayment": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/processPayment',
            "travelPolicy/getAgents": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/getAgents',
            "travelPolicy/getCoverages": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/getCoverages',
            "travelPolicy/saveQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/saveQuote',
            "travelPolicy/SearchResult": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/SearchResult',
            "getOccupationsDIT": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getOccupations',
            "rejectMessageDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/rejectMessageDetails',
            "regenerateOtpforHealthCombi": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/regenerateOtpforHealthCombi',
            "dedupeCheck": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/dedupeCheck',
            "viewRenewingPolicyDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/viewRenewingPolicyDetails',
            "otpValidateforDBSUser": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/otpValidateforDBSUser',
            "fetchProductForPartnerForNB": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchProductForPartnerForNB',
            "printCoverSheet": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/printCoverSheet',
            "getProposalNotesForInternal": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getProposalNotesForInternal',
            "saveLatestRNQuote": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/saveLatestRNQuote',
            "getProposalStatus": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getProposalStatus',
            "getProposalNotesForAgent": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getProposalNotesForAgent',
            "getVIRGlobalSearchInfo": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getVIRGlobalSearchInfo',
            "checkDSARefNumber": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/checkDSARefNumber',
            "searchCustomerFromMaster": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/searchCustomerFromMaster',
            "approveZone2Referral": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/approveZone2Referral',
            "updateLoanAccountNumber": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/updateLoanAccountNumber',
            "getFinancierGSTIN": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getFinancierGSTIN',
            "fetchEnquiryAgents": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/fetchEnquiryAgents',
            "postEndorsementHealthDetails": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/postEndorsementHealthDetails',
            "getOARenewalStatus": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getOARenewalStatus',
            "generateRenewalNoticePrint": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/generateRenewalNoticePrint',
            "updateReason": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/updateReason',
            "changePassword": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/changePassword',
            "getUserMailId": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getUserMailId',
            "getOtpforMail": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getOtpforMail',
            "getOtpforPassword": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getOtpforPassword',
            "validateOtp": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/validateOtp',
            "regenerateOtp": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/regenerateOtp',
            "changeEmail": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/changeEmail',
            "isOtpSent": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/isOtpSent',
            "getSublineBranches": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/getSublineBranches',
            "validateLivesCovered": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/validateLivesCovered',
            "travelPolicy/getQuickRating": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/getQuickRating',
            "travelPolicy/getCountryGroupsForPlanModified": this.globals.BACKEND_URL_PREFIX + this.globals.CONTEXT_PATH + '/travelPolicy/getCountryGroupsForPlanModified'
            
               

        },
        "wso2": {
            "loginUserDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/LoginUserDetailsService/loginUserDetails',
            "getCitiesAndStates": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CitiesAndStatesService/getCitiesAndStates',
            "getStateByCityCode": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/StateByCityCodeService/getStateByCityCode',
            "getGSTStateCode": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GSTStateCodeService/getGSTStateCode',
            "getBranchMasterDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/BranchMasterDetailsService/getBranchMasterDetails',
            "getInternalAgentDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/InternalAgentDetailsService/getInternalAgentDetails',
            "getAgentDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AgentDetailsService/getAgentDetails',
            "getPartieDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PartieDetailsService/getPartieDetails',
            "fetchPartyDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchPartyDetailsService/fetchPartyDetails',
            "getBDO": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/BDOService/getBDO',
            "getAgentBDO": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AgentBDOService/getAgentBDO',
            "getOccupation": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/OccupationService/getOccupation',
            "getPOS": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/POSService/getPOS',
            "getPosAgentDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PosAgentDetailsService/getPosAgentDetails',
            "getCoverNotes": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CoverNotesServices/getCoverNotes',
            "getCoverNoteDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CoverNoteDetailsService/getCoverNoteDetails',
            "getInsuranceRepositories": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/InsuranceRepositoriesService/getInsuranceRepositories',
            "getRTO": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/RTOService/getRTO',
            "getRegRegionZone": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/RegRegionZoneService/getRegRegionZone',
            "getAvailableMakes": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AvailableMakesService/getAvailableMakes',
            "getModelData": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ModelDataService/getModelData',
            "getModelsForMake": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ModelsForMakeService/getModelsForMake',
            "getTechnicalDiscountDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TechnicalDiscountDetailsService/getTechnicalDiscountDetails',
            "getServiceProviders": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ServiceProvidersService/getServiceProviders',
            "getAutoAssociations": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AutoAssociationsService/getAutoAssociations',
            "getAddonCoverageForExternalUser": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AddonCoverageForExternalUserService/getAddonCoverageForExternalUser',
            "getCampaignDiscounts": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CampaignDiscountsService/getCampaignDiscounts',
            "getFraudReasons": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FraudReasonsservice/getFraudReasons',
            "getMasterData": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MasterDataService/getMasterData',
            "getPreviousInsurers": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PreviousInsurersService/getPreviousInsurers',
            "getCompanyBranches": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CompanyBranchesService/getCompanyBranches',
            "getCompanyBranchAddress": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CompanyBranchAddressService/getCompanyBranchAddress',
            "getCommissionDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CommissionDetailsService/getCommissionDetails',
            "getMotorCoverages": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MotorCoveragesService/getMotorCoverages',
            "getHealthCoverages": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/HealthCoveragesService/getHealthCoverages',
            "getFloaterRelations": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FloaterRelationsService/getFloaterRelations',
            "getHomeCoverages": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/HomeCoveragesService/getHomeCoverages',
            "getPincodeMasterDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PincodeMasterDetailsService/getPincodeMasterDetails',
            "getOccupations": `${this.globals.URLPREFIXHOME}getOccupations`,
            "getMasterOccupations": `${this.globals.URLPREFIXHOME}getMasterOccupations`,
            "saveMotorQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SaveMotorQuoteService/saveMotorQuote',
            "getAgents": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AgentsService/getAgents',
            "searchParties": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SearchPartiesService/searchParties',
            "getExternalCoverNoteDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ExternalCoverNoteDetailsService/getExternalCoverNoteDetails',
            "getNomineeRelationship": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/NomineeRelationshipService/getNomineeRelationship',
            "fetchSchemeCodeList": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchSchemeCodeListService/fetchSchemeCodeList',
            "getTrailerMakes": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TrailerMakesService/getTrailerMakes',
            "getTrailerModels": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TrailerModelsService/getTrailerModels',
            "getCampaignDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CampaignDetailsService/getCampaignDetails',
            "checkGroupCampaign": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CheckGroupCampaignService/checkGroupCampaign',
            "fetchProductForPolicyForNB": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchProductForPolicyForNBService/fetchProductForPolicyForNB',
            "getLivesCoveredCampaigns": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/LivesCoveredCampaignsService/getLivesCoveredCampaigns',
            "getPlansForCampaign": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PlansForCampaignService/getPlansForCampaign',
            "getIdentityProofs": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/IdentityProofsService/getIdentityProofs',
            "getResidenceProofs": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ResidenceProofsService/getResidenceProofs',
            "getRiders": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/RidersService/getRiders',
            "getPreAilments": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PreAilmentsService/getPreAilments',
            "getICDDesc": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ICDDescService/getICDDesc',
            "saveHealthQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SaveHealthQuoteService/saveHealthQuote',
            "updateCheckListFilled": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/UpdateCheckListFilledService/updateCheckListFilled',
            "saveHomeQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SaveHomeQuoteService/saveHomeQuote',
            "getAdditionalInfoPropForAgents": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AdditionalInfoPropForAgentsService/getAdditionalInfoPropForAgents',
            "getGender": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GenderService/getGender',
            "checkIfCheckListFilled": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CheckIfCheckListFilledService/checkIfCheckListFilled',
            "getChkList": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ChkListService/getChkList',
            "searchHealthPolicy": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SearchHealthPolicyService/searchHealthPolicy',
            "getMasterPlanList": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MasterPlanList/getMasterPlanList',
            "getMasterSubPlanList": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MasterSubPlanListService/getMasterSubPlanList',
            "getFOSProductPlans": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FOSProductPlansService/getFOSProductPlans',
            "showCoverageOptionPartner": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ShowCoverageOptionPartnerService/showCoverageOptionPartner',
            "getCampaignNames": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CampaignNamesService/getCampaignNames',
            "getProducts": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ProductsService/getProducts`,
            "getAgentProducts": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AgentProductsService/getAgentProducts',
            "isCombiProduct": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/IsCombiProductService/isCombiProduct',
            "fetchCombiSumInsureds": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchCombiSumInsuredsService/fetchCombiSumInsureds',
            "getInsuranceCompanyNames": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/InsuranceCompanyNamesService/getInsuranceCompanyNames',
            "getICDCodeFromMasterDisease": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ICDCodeFromMasterDiseaseService/getICDCodeFromMasterDisease',
            "getPEPName": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PEPNameService/getPEPName',
            "getNameFromCommonItem": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/NameFromCommonItemService/getNameFromCommonItem',
            "getPreviousPolicyDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PreviousPolicyDetailsService/getPreviousPolicyDetails',
            "mobileNumberValidation": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MobileNumberValidationService/mobileNumberValidation',
            "getBreakInLoading": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/BreakInLoadingService/getBreakInLoading',
            "getReasons": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ReasonsService/getReasons',
            "checkCombiCampaign": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CheckCombiCampaignService/checkCombiCampaign',
            "cancelQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CancelQuoteService/cancelQuote',
            "fetchQuestions": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchQuestionsService/fetchQuestions',
            "getBanks": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/BanksService/getBanks',
            "getBodyType": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/BodyTypeService/getBodyType',
            "getHypothecation": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/HypothecationService/getHypothecation',
            "getMessageDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MessageDetailsService/getMessageDetails',
            "approveMessageDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ApproveMessageDetailsService/approveMessageDetails',
            "getSublineForInsPolicy": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SublineForInsPolicyService/getSublineForInsPolicy',
            "getModuleDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ModuleDetailsService/getModuleDetails',
            "getMessages": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/MessagesService/getMessages',
            "getPolicyId": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/PolicyIdService/getPolicyId`,
            "fetchTasks": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/FetchTasksService/fetchTasks`,
            "releaseTask": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}` + `/ReleaseTaskService/releaseTask`,
            "getDITCampaigns": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/DITCampaignsService/getDITCampaigns`,
            "getInwardDetails": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/InwardDetailsService/getInwardDetails`,
            "getDetails": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/DetailsService/getDetails`,
            "viewReasons": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ViewReasonsService/viewReasons`,
            "processShortfallCollected": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ProcessShortfallCollectedService/processShortfallCollected`,
            "viewHistory": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ViewHistoryService/viewHistory`,
            "viewHumsErrors": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ViewHumsErrorsService/viewHumsErrors`,
            "viewComments": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ViewCommentsService/viewComments`,
            "getInfopendingReasons": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/InfopendingReasonsService/getInfopendingReasons`,
            "getUserAgentSegmentMappings": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/UserAgentSegmentMappingsService/getUserAgentSegmentMappings`,
            "getRmCode": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/RmCodeService/getRmCode`,
            "getBDOCode": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/BDOCodeServices/getBDOCode`,
            "getPolicyIds": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/PolicyIdsService/getPolicyIds`,
            "createReceiptNo": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/createReceiptNoService/createReceiptNo`,
            "approveChequeDishonourInward": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/ApproveChequeDishonourInwardService/approveChequeDishonourInward`,
            "createInward": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/CreateInwardService/createInward`,
            "inwardSummaryPage": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/InwardSummaryPageService/inwardSummaryPage`,
            "saveEditDetails": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SaveEditDetailsService/saveEditDetails`,
            "getUploadedDocuments": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/UploadedDocumentsService/getUploadedDocuments`,
            "searchInward": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SearchInwardService/searchInward`,
            "sentforProcessing": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SentforProcessingService/sentforProcessing`,
            "sendToInfoPending": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SendToInfoPendingService/sendToInfoPending`,
            "sentToInvalid": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SentToInvalidService/sentToInvalid`,
            "revokeProposal": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/RevokeProposalService/revokeProposal`,
            "sentToRefund": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SentToRefundService/sentToRefund`,
            "documentUpload": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/DocumentUploadService/documentUpload`,
            "searchChequeDishonourInward": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/SearchChequeDishonourInwardService/searchChequeDishonourInward`,
            "generateChequeDishonourPdf": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GenerateChequeDishonourPdfService/generateChequeDishonourPdf',
            "getAvaliableEndorsements": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AvaliableEndorsementsService/getAvaliableEndorsements',
            "getClaimDetailsService": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ClaimDetailsService/getClaimDetailsService',
            "getHealthCombiCoveragesandQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/HealthCombiCoveragesandQuoteService/getHealthCombiCoveragesandQuote',
            "loadPolicy": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/LoadPolicyService/loadPolicy',
            "getHealthCombiOTPValidate": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/HealthCombiOTPValidateService/getHealthCombiOTPValidate',
            "getOtpforHealthCombi": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + `/OtpforHealthCombiService/getOtpforHealthCombi`,
            "customerApprove": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + `/CustomerApproveService/customerApprove`,
            "sendToFinance": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + `/SendToFinanceService/sendToFinance`,
            "getOTPAcceptAndPendingCases": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + `/OTPAcceptAndPendingCasesService/getOTPAcceptAndPendingCases`,
            "getPolicyHistory": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PolicyHistoryService/getPolicyHistory',
            "postEndorsementDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PostEndorsementDetailsService/postEndorsementDetails',
            "getPolicyDetailsForEndorsement": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PolicyDetailsForEndorsementService/getPolicyDetailsForEndorsement',
            "getExpiryDate": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ExpiryDateService/getExpiryDate',
            "getProposalDocuments": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ProposalDocumentsService/getProposalDocuments',
            "getPayementModes": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PayementModesService/getPayementModes',
            "getAllReceiptsForPolicies": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AllReceiptsForPoliciesService/getAllReceiptsForPolicies',
            "submitPayment": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + `/TravelPolicySubmitPaymentService/travelPolicy/submitPayment`,
            "getPolicyDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + `/TravelPolicyPolicyDetailsService/travelPolicy/getPolicyDetails`,
            "sendLinktoCustomer": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SendLinktoCustomerService/sendLinktoCustomer',
            "searchPolicy": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SearchPolicyService/searchPolicy',
            "saveAndProcess": `${this.globals.URLPREFIX}${this.globals.CONTEXT_PATH_WSO2}/saveAndProcessService/saveAndProcess`,
            "finalizeEndorsement": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FinalizeEndorsementService/finalizeEndorsement',
            "deleteEndorsement": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/DeleteEndorsementService/deleteEndorsement',
            "getViewAddonCovers": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ViewAddonCoversService/getViewAddonCovers',
            "generatePrint": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GeneratePrintServiceForESB/generatePrint',
            "generateAutoReceipt": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GenerateAutoReceiptService/generateAutoReceipt',
            "getAlertMessageReason": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/AlertMessageReasonService/getAlertMessageReason',
            "processPayment": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ProcessPaymentService/processPayment',
            "travelPolicy/getAgents": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TravelPolicyAgents/travelPolicy/getAgents',
            "travelPolicy/getCoverages": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TravelPolicyCoveragesService/travelPolicy/getCoverages',
            "travelPolicy/saveQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TravelPolicySaveQuoteService/travelPolicy/saveQuote',
            "travelPolicy/SearchResult": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TravelPolicySearchResultService/travelPolicy/SearchResult',
            "getOccupationsDIT": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/OccupationsService/getOccupations',
            "rejectMessageDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/RejectMessageDetailsService/rejectMessageDetails',
            "regenerateOtpforHealthCombi": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/RegenerateOtpforHealthCombiService/regenerateOtpforHealthCombi',
            "dedupeCheck": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/DedupeCheckService/dedupeCheck',
            "viewRenewingPolicyDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ViewRenewingPolicyDetailsService/viewRenewingPolicyDetails',
            "otpValidateforDBSUser": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/OtpValidateforDBSUserService/otpValidateforDBSUser',
            "fetchProductForPartnerForNB": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchProductForPartnerForNBService/fetchProductForPartnerForNB',
            "printCoverSheet": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/PrintCoverSheetService/printCoverSheet',
            "getProposalNotesForInternal": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ProposalNotesForInternalService/getProposalNotesForInternal',
            "saveLatestRNQuote": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SaveLatestRNQuoteService/saveLatestRNQuote',
            "getProposalStatus": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ProposalStatusService/getProposalStatus',
            "getProposalNotesForAgent": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ProposalNotesForAgentService/getProposalNotesForAgent',
            "getVIRGlobalSearchInfo": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/VIRGlobalSearchInfoService/getVIRGlobalSearchInfo',
            "checkDSARefNumber": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CheckDSARefNumberService/checkDSARefNumber',
            "searchCustomerFromMaster": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/TravelPolicySearchCustomerFromMasterService/travelPolicy/searchCustomerFromMaster',
            "approveZone2Referral": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ApproveZone2ReferralService/approveZone2Referral',
            "updateLoanAccountNumber": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/UpdateLoanAccountNumberService/updateLoanAccountNumber',
            "getFinancierGSTIN": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FinancierGSTINService/getFinancierGSTIN',
            "fetchEnquiryAgents": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/FetchEnquiryAgentsService/fetchEnquiryAgents',
            "postEndorsementHealthDetails": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/EndorsementHealthDetailsService/postEndorsementHealthDetails',
            "getOARenewalStatus": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/OARenewalStatusService/getOARenewalStatus',
            "generateRenewalNoticePrint": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GenerateRenewalNoticePrintService/generateRenewalNoticePrint',
            "updateReason": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/UpdateReasonService/updateReason',
            "changePassword": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ChangePasswordService/changePassword',
            "changeEmail": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ChangeEmailService/changeEmail',
            "regenerateOtp": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/RegenerateOtpService/regenerateOtp',
            "validateOtp": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ValidateOtpService/validateOtp',
            "getOtpforPassword": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GetOtpforPasswordService/getOtpforPassword',
            "getOtpforMail": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GetOtpforMailService/getOtpforMail',
            "getUserMailId": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/GetUserMailIdService/getUserMailId',
            "isOtpSent": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/IsOtpSentService/isOtpSent',
            "getSublineBranches": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/SublineBranchesService/getSublineBranches',
            "validateLivesCovered": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/ValidateLivesCoveredService/validateLivesCovered',
            "travelPolicy/getQuickRating": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/QuickRatingService/travelPolicy/getQuickRating',
            "travelPolicy/getCountryGroupsForPlanModified": this.globals.URLPREFIX + this.globals.CONTEXT_PATH_WSO2 + '/CountryGroupsForPlanModifiedService/travelPolicy/getCountryGroupsForPlanModified'
            
        }
    }

    public filteredEndPoints = this.globals.EnableWSO2EndPoints ? this.apiUrls.wso2 : this.apiUrls.eapps;
}